name: "Build"

on:
  pull_request:
    branches:
      - master

jobs:
<<<<<<< HEAD
  install:
=======
  size:
>>>>>>> parent of fb23553... Fix step names
    runs-on: ubuntu-16.04
    env:
      CI_JOB_NUMBER: 1

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      id: npm-cache
      uses: actions/cache@v1
      env:
        cache-name: build
      with:
        path: node_modules
        key:  ${{ runner.os }}-npm-cache-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-${{ env.cache-name }}-
          ${{ runner.os }}-npm-cache-

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install --no-audit --no-fund

  build:
    runs-on: ubuntu-16.04
    needs: install

    steps:
      - name: Build
        run: npm run build

      - uses: andresz1/size-limit-action@v1.3.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build

  test:
    runs-on: ubuntu-16.04
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Check type errors
        run: npx tsc --noEmit

      - name: Run tests and generate code coverage report
        run: npm test -- --coverage

      - uses: codecov/codecov-action@v1
        with:
          file: coverage/clover.xml
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
