name: "size"

on:
  pull_request:
    branches:
      - master

jobs:
  size:
    runs-on: ubuntu-16.04
    env:
      CI_JOB_NUMBER: 1
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install

    - uses: andresz1/size-limit-action@v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run size-limit
      run: npm run size
