name: "Size limit"

on:
  pull_request:
    branches:
      - master

jobs:
  size:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install --no-audit --no-fund

    - uses: andresz1/size-limit-action@v1.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
