name: "size"

on:
  pull_request:
    branches:
      - master

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    step:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
